### ISSUE TITLE
calendar installation error

### ISSUE THREAD

**Issue by gkim132** [GrocerCheck/LivePopularTimes#2]
ERROR: Could not find a version that satisfies the requirement calendar (from LivePopularTimes==1.1) (from versions: 
none)
ERROR: No matching distribution found for calendar (from LivePopularTimes==1.1)

**Comment by ihasdapie** [comment]
Please try installing LivePopularTimes==1.3 or LivePopularTimes==1.0

I had made a mistake in the packaging of 1.1. Thank you for bringing this to my attention
